version: '3'
services:
  frontend:
    container_name: frontend
    image:
      front
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: backend
    image:
      back
    ports:
      - 8000:8000
    restart: always