version: '3'
services:
  frontend:
    container_name: frontend
    build:
      context: ./fronthack
    ports:
      - 3000:3000
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: ./backhack
    ports:
      - 8000:8000
    restart: always